services:
  - type: web
    name: jump-checkin
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir jump_checkin jump_checkin.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jump-checkin-db
          property: connectionString

databases:
  - name: jump-checkin-db
    plan: free